<?php

/*
Copyright (C) 2006  Myron Turner

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

*/

/**
 *
 * @category   XML
 * @package    XML_PullParser_NS
 * @author     Myron Turner <Myron_Turner@shaw.ca>
 * @copyright  2006 Myron Turner
 * @license    http://www.gnu.org/copyleft/lesser.html   LGPL License 2.1 
 * @version    1.0.2
 *
*/

require_once "XML_PullParser.inc";

/**
 * XML_PullParser_NS adds namespace support to XML_PullParser.
 *  
 * @package XML_PullParser_NS 
 * @author Myron Turner <Myron_Turner@shaw.ca>
  * @version    1.0.2   
 *
*/

XML_PullParser_NamespaceSupport(true);

class XML_PullParser_NS extends XML_PullParser {

  


}



?>
